"""added link column to suggestion table

Revision ID: 83eca4d701f2
Revises: 584c8ab17680
Create Date: 2022-09-13 14:33:42.124125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83eca4d701f2'
down_revision = '584c8ab17680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('link', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestion', 'link')
    # ### end Alembic commands ###
